"""Generate Lean certificate files STUProof/HookCert{n}.lean (P-LEAN-DBL) from the exact odd
hook decompositions certs/hookdec_n{n}.txt, mirroring STUProof/HookCertificates.lean (n <= 20):
common denominator D, natural numbers y = D * x in a dense table tbl[a][s][i]
(a < n, s <= a, i < n - s). The constraints of IsHookDecompositionNat are checked in Lean by
`decide +kernel`, split into 3n pieces (runs and rows of each hook a, cells of each run s; see
STUProof/HookCertSplit.lean) that are elaborated one after the other (`Elab.async false`), which
keeps the kernel's memory bounded (a single check of all constraints of n = 39 needs > 7.5 GB).

Each certificate is first re-checked with an independent checker
(stu3/coord_check_hook.py) and the scaled integer table is re-checked here against the exact
integer conditions of IsHookDecompositionNat.

usage: python gen_lean_certs.py [n ...]      (default: 21 23 ... 39)
"""
import os
import sys
from collections import defaultdict
from fractions import Fraction as F
from math import lcm

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'stu3'))
from coord_check_hook import check as indep_check  # noqa: E402

LEAN_DIR = os.path.join(HERE, '..', '..', '..', 'formal-conjectures', 'STUProof')


def load(n, path):
    x = defaultdict(F)
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            a, s, i, v = line.split()
            x[(int(a), int(s), int(i))] += F(v)
    return x


def nat_check(n, D, y):
    """The integer conditions of IsHookDecompositionNat n D y (y[a][s][i], dense)."""
    g = lambda a, s, i: y[a][s][i] if (a < n and s <= a and i < n - s) else 0
    for a in range(n):
        for s in range(a + 1):
            assert sum(g(a, s, i) for i in range(n - s)) == D, ('run', a, s)
        for r in range(n):
            tot = g(a, 0, r)
            for s in range(1, a + 1):
                tot += (g(a, s, r) if r + s <= n - 1 else 0) + (g(a, s, r - s) if s <= r else 0)
            assert n * tot == (2 * a + 1) * D, ('row', a, r)
    for s in range(n):
        for i in range(n - s):
            assert sum(g(a, s, i) for a in range(s, n)) == D, ('cell', s, i)


def lean_list(items):
    """Lean list literal. Lists with at least 32 entries are written as `::` chains (the `[...]`
    macro expands such long literals into untyped `let`s; for n = 39 the `[...]` version of the
    data hit the default maxRecDepth)."""
    if len(items) < 32:
        return '[' + ', '.join(items) + ']'
    return '(' + ' :: '.join(items) + ' :: [])'


def gen(n):
    src = os.path.join(HERE, 'certs', f'hookdec_n{n}.txt')
    assert indep_check(n, src)
    x = load(n, src)
    D = 1
    for v in x.values():
        D = lcm(D, v.denominator)
    y = [[[int(x[(a, s, i)] * D) for i in range(n - s)] for s in range(a + 1)] for a in range(n)]
    for (a, s, i), v in x.items():
        assert v * D == y[a][s][i] and v >= 0
    nat_check(n, D, y)
    hooks = [lean_list([lean_list([str(v) for v in r]) for r in y[a]]) for a in range(n)]
    if n < 32:
        rows = '  [\n' + ',\n'.join('    ' + h for h in hooks) + '\n  ]'
    else:
        rows = ' ::\n'.join('    ' + h for h in hooks) + ' :: []'
    y_ = f'(hookNatX hookNat{n})'
    pieces = []
    for kind, pred in (('run', 'HookRunNat'), ('row', 'HookRowNat'), ('cell', 'HookCellNat')):
        for k in range(n):
            pieces.append(f"""theorem hookNat{n}_{kind}_{k} : {pred} {n} {D} {y_} {k} := by
  unfold {pred}
  decide +kernel
""")

    def chain(kind):
        t = 'forall_lt_zero _'
        for k in range(n):
            t = f'forall_lt_succ_of ({t}) hookNat{n}_{kind}_{k}'
        return t

    pieces_text = chr(10).join(pieces)
    text = f'''import STUProof.HookCertSplit

/-!
# Hook decomposition of the {n}-box (exact certificate)

The data are the exact rational hook decomposition of P-HOOK
(`iqoqi/programs/hook/certs/hookdec_n{n}.txt`, verified by the independent checker
`stu3/coord_check_hook.py`), scaled by the common denominator `D` to natural numbers
(generated by `iqoqi/programs/hook/gen_lean_certs.py`). Every constraint of
`IsHookDecompositionNat` is checked by the Lean kernel (`decide +kernel`), split into the runs and
rows of each hook and the cells of each run (`STUProof/HookCertSplit.lean`). The pieces are
elaborated one after the other (`Elab.async false`), so that only one kernel check is in memory at
a time.
-/

namespace STUProof

set_option Elab.async false
set_option maxRecDepth 1000000

/-- Exact hook decomposition of the {n}-box, scaled by `{D}` (data of
`hook/certs/hookdec_n{n}.txt`). -/
def hookNat{n} : List (List (List ℕ)) :=
{rows}

{pieces_text}
theorem hookNat{n}_valid : IsHookDecompositionNat {n} {D} {y_} :=
  isHookDecompositionNat_of_split
    ({chain('run')})
    ({chain('row')})
    ({chain('cell')})

theorem hookDecomposition_{n} : HookDecomposition {n} :=
  hookDecomposition_of_nat (by norm_num) hookNat{n}_valid

end STUProof
'''
    out = os.path.join(LEAN_DIR, f'HookCert{n}.lean')
    with open(out, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print(f'n={n}: D has {len(str(D))} digits, {sum(1 for v in x.values() if v)} nonzero entries '
          f'-> {os.path.normpath(out)} ({len(text)} bytes)', flush=True)


if __name__ == '__main__':
    ns = [int(a) for a in sys.argv[1:]] or list(range(21, 40, 2))
    for n in ns:
        gen(n)
